var express = require('express')
routes = express.Router()
var userController=require('../controller/registration')
var loginController=require('../controller/registration')
var courseController=require('../controller/course')
var adminController=require('../controller/admin')
var tutorController=require('../controller/tutor')
var videoController=require('../controller/addvideo')
var documentController=require('../controller/addDocument')
var libraryController=require('../controller/library')
var studentController=require('../controller/student')
var updateprofileController=require('../controller/profileupdate')
var findcourseController=require('../controller/course')
var finduserController=require('../controller/registration')
var updatePassController=require('../controller/profileupdate')
var dispcourseController=require('../controller/course')
var dispselcourseController=require('../controller/course')
var dispuserController=require('../controller/registration')
var coursetypeController=require('../controller/course')
var topicController=require('../controller/course')
var disptypeController=require('../controller/course')
var searchCourseController=require('../controller/course')
var bookingController=require('../controller/course')
var getcourseController=require('../controller/course')
var disptopicController=require('../controller/course')
var dispvideoController=require('../controller/addvideo')
var selvideoController=require('../controller/addvideo')
var paymentController=require('../controller/course')
var getBookingController=require('../controller/course')
var searchController=require('../controller/course')
var courseListController=require('../controller/course')
var addCommentController=require('../controller/addvideo')
var CommentReplyController=require('../controller/addvideo')
var dispCommentController=require('../controller/addvideo')
var dispDocumentController=require('../controller/addDocument')
var deleteUserController=require('../controller/registration')
var acceptUserController=require('../controller/registration')
var sendmessageController=require('../controller/chat')
var dispchatController=require('../controller/chat')
var complainttypeController=require('../controller/complaint')
var dispcomplainttypeController=require('../controller/complaint')
var complaintController=require('../controller/complaint')
var deletetutorController=require('../controller/tutor')
var deletestudentController=require('../controller/student')
var acceptcourseController=require('../controller/course')
var complaintListController=require('../controller/complaint')
var complaintReplyController=require('../controller/complaint')
var reportController=require('../controller/course')
var userreportController=require('../controller/registration')
var dispTutorController=require('../controller/tutor')
var dispstudentController=require('../controller/student')
var bookingstatusController=require('../controller/course')

routes.post('/register',userController.addUser)
routes.post('/login',loginController.login)
routes.post('/addCourse',courseController.addCourse)
routes.post('/AdminRegistration',adminController.addAdmin)
routes.post('/TutorRegistration',tutorController.addTutor)
routes.post('/addVideo',videoController.addVideo)
routes.post('/addDocument',documentController.addDocument)
routes.post('/addLibrary',libraryController.addLibrary)
routes.post('/addStudent',studentController.addStudent)
routes.post('/updateProfile',updateprofileController.updateProfile)
routes.post('/findCourse',findcourseController.findCourse)
routes.post('/findUser',finduserController.findUser)
routes.post('/updatePassword',updatePassController.updatePassword)
routes.post('/dispCourse',dispcourseController.dispCourse)
routes.post('/selectCourse',dispselcourseController.selectCourse)
routes.post('/dispUsers',dispuserController.dispUsers)
routes.post('/addCoursetype',coursetypeController.addCoursetype)
routes.post('/addTopic',topicController.addTopic)
routes.post('/dispType',disptypeController.dispType)
routes.post('/searchCourse',searchCourseController.searchCourse)
routes.post('/bookingCourse',bookingController.bookingCourse)
routes.post('/getCourse',getcourseController.getCourse)
routes.post('/dispTopic',disptopicController.dispTopic)
routes.post('/dispVideo',dispvideoController.dispVideo)
routes.post('/selVideo',selvideoController.selVideo)
routes.post('/payment',paymentController.addPayment)
routes.post('/getBookings',getBookingController.getBookings)
routes.post('/search',searchController.Search)
routes.post('/courseList',courseListController.CourseList)
routes.post('/addComment',addCommentController.addComment)
routes.post('/commentReply',CommentReplyController.commentReply)
routes.post('/dispComment',dispCommentController.dispComment)
routes.post('/dispDocument',dispDocumentController.dispDocuments)
routes.post('/deleteUser',deleteUserController.deleteUsers)
routes.post('/acceptUser',acceptUserController.acceptUser)
routes.post('/sendMessage',sendmessageController.sendMessage)
routes.post('/dispChat',dispchatController.dispChat)
routes.post('/addComplainttype',complainttypeController.addComplainttype)
routes.post('/dispComplaintType',dispcomplainttypeController.dispComplaintType)
routes.post('/addComplaint',complaintController.addComplaint)
routes.post('/deleteTutor',deletetutorController.deleteTutor)
routes.post('/deleteStudent',deletestudentController.deleteStudent)
routes.post('/acceptCourse',acceptcourseController.acceptCourse)
routes.post('/complaintList',complaintListController.ComplaintList)
routes.post('/addComplaintReply',complaintReplyController.addComplaintReply)
routes.post('/bookingReport',reportController.BookingReport)
routes.post('/userReport',userreportController.userReport)
routes.post('/dispTutor',dispTutorController.dispTutor)
routes.post('/dispStudent',dispstudentController.dispStudent)
routes.post('/paymentStatus',bookingstatusController.paymentStatus)
routes.post('/dispComplaintReply',complaintReplyController.dispComplaintReply)
routes.post('/dispTopic2',disptopicController.dispTopic2)
routes.post('/deleteType',coursetypeController.deleteType)
routes.post('/deleteTopic',topicController.deleteTopic)
routes.post('/deleteTopic2',topicController.deleteTopic2)
routes.post('/bookingReport2',reportController.BookingReport2)

module.exports = routes