var express = require('express')
routes = express.Router()
var userController=require('../controller/registration')
var loginController=require('../controller/registration')
var courseController=require('../controller/course')
var adminController=require('../controller/admin')
var tutorController=require('../controller/tutor')
var videoController=require('../controller/addvideo')
var documentController=require('../controller/addDocument')
var libraryController=require('../controller/library')
var userupController=require('../controller/user')
var updateprofileController=require('../controller/profileupdate')
var findcourseController=require('../controller/course')
var finduserController=require('../controller/registration')
var updatePassController=require('../controller/profileupdate')
var dispcourseController=require('../controller/course')
var dispselcourseController=require('../controller/course')
var dispuserController=require('../controller/registration')
var coursetypeController=require('../controller/course')
var topicController=require('../controller/course')
var disptypeController=require('../controller/course')
var searchCourseController=require('../controller/course')
var bookingController=require('../controller/course')
var getcourseController=require('../controller/course')
var disptopicController=require('../controller/course')
var dispvideoController=require('../controller/addvideo')
var selvideoController=require('../controller/addvideo')
var paymentController=require('../controller/course')
var getBookingController=require('../controller/course')
var searchController=require('../controller/course')
var courseListController=require('../controller/course')
var addCommentController=require('../controller/addvideo')
var CommentReplyController=require('../controller/addvideo')
var dispCommentController=require('../controller/addvideo')
var dispDocumentController=require('../controller/addDocument')
var deleteUserController=require('../controller/registration')
var acceptUserController=require('../controller/registration')

routes.post('/register',userController.addUser)
routes.post('/login',loginController.login)
routes.post('/addCourse',courseController.addCourse)
routes.post('/AdminRegistration',adminController.addAdmin)
routes.post('/TutorRegistration',tutorController.addTutor)
routes.post('/addVideo',videoController.addVideo)
routes.post('/addDocument',documentController.addDocument)
routes.post('/addLibrary',libraryController.addLibrary)
routes.post('/userUp',userupController.userUp)
routes.post('/updateProfile',updateprofileController.updateProfile)
routes.post('/findCourse',findcourseController.findCourse)
routes.post('/findUser',finduserController.findUser)
routes.post('/updatePassword',updatePassController.updatePassword)
routes.post('/dispCourse',dispcourseController.dispCourse)
routes.post('/selectCourse',dispselcourseController.selectCourse)
routes.post('/dispUsers',dispuserController.dispUsers)
routes.post('/addCoursetype',coursetypeController.addCoursetype)
routes.post('/addTopic',topicController.addTopic)
routes.post('/dispType',disptypeController.dispType)
routes.post('/searchCourse',searchCourseController.searchCourse)
routes.post('/bookingCourse',bookingController.bookingCourse)
routes.post('/getCourse',getcourseController.getCourse)
routes.post('/dispTopic',disptopicController.dispTopic)
routes.post('/dispVideo',dispvideoController.dispVideo)
routes.post('/selVideo',selvideoController.selVideo)
routes.post('/payment',paymentController.addPayment)
routes.post('/getBookings',getBookingController.getBookings)
routes.post('/search',searchController.Search)
routes.post('/courseList',courseListController.CourseList)
routes.post('/addComment',addCommentController.addComment)
routes.post('/commentReply',CommentReplyController.commentReply)
routes.post('/dispComment',dispCommentController.dispComment)
routes.post('/dispDocument',dispDocumentController.dispDocuments)
routes.post('/deleteUser',deleteUserController.deleteUsers)
routes.post('/acceptUser',acceptUserController.acceptUser)

module.exports = routes