// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv96wPo-N44KotOW1_BfeNqxyKY5qL1uM',
    appId: '1:654233174495:web:2c7b06af487608cd12046a',
    messagingSenderId: '654233174495',
    projectId: 'newproject-7688b',
    authDomain: 'newproject-7688b.firebaseapp.com',
    storageBucket: 'newproject-7688b.appspot.com',
    measurementId: 'G-ZQPRN0E46D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc2cGQyR6KhEZl8RArwmpHwvFI8fh7GAA',
    appId: '1:654233174495:android:4922f99ccb1417c712046a',
    messagingSenderId: '654233174495',
    projectId: 'newproject-7688b',
    storageBucket: 'newproject-7688b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6rJy8iF1I8NSf6138mZO3h5NHLCwDSy0',
    appId: '1:654233174495:ios:d82f822094a3b83312046a',
    messagingSenderId: '654233174495',
    projectId: 'newproject-7688b',
    storageBucket: 'newproject-7688b.appspot.com',
    iosClientId: '654233174495-jog0ujkpurhvctk0ov3lm6ka1l86cpve.apps.googleusercontent.com',
    iosBundleId: 'com.example.signup1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6rJy8iF1I8NSf6138mZO3h5NHLCwDSy0',
    appId: '1:654233174495:ios:d82f822094a3b83312046a',
    messagingSenderId: '654233174495',
    projectId: 'newproject-7688b',
    storageBucket: 'newproject-7688b.appspot.com',
    iosClientId: '654233174495-jog0ujkpurhvctk0ov3lm6ka1l86cpve.apps.googleusercontent.com',
    iosBundleId: 'com.example.signup1',
  );
}
